const ACTION_TYPE={
    SORT_TYPE:"SORT_TYPE",
    CATEGORY:"CATEGORY",
    RANGE:"FILTER_BY_RANGE",
    RATE:"FILTER_BY_RATE",
    RESET:"RESET",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    INCR_QTY:"INCR_QTY",
    DECR_QTY:"DECR_QTY"
}

export {ACTION_TYPE}