const ACTION_TYPE={
    SORT_TYPE:"SORT_TYPE",
    SEARCH:"SEARCH",
    CATEGORY:"CATEGORY",
    RANGE:"FILTER_BY_RANGE",
    RATE:"FILTER_BY_RATE",
    RESET:"RESET",
    ADD_TO_CART:"ADD_TO_CART",
    REMOVE_FROM_CART:"REMOVE_FROM_CART",
    INCR_QTY:"INCR_QTY",
    DECR_QTY:"DECR_QTY",
    ADD_TO_WISHLIST:"ADD_TO_WISHLIST",
    REMOVE_FROM_WISHLIST:"REMOVE_FROM_WISHLIST",
    PRICE_DETAILS:"PRICE_DETAILS",
    ADDRESS_DETAILS:"ADDRESS_DETAILS",
    ORDER_COMPLETE:"ORDER_COMPLETE",
    CLEAR_CART:"CLEAR_CART",
    ADD_ADDRESS:"ADD_ADDRESS",
    DELETE_ADDRESS:"DELETE_ADDRESS",
}

export {ACTION_TYPE}